Mnemos/Controllers/ThemesController.cs
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Mnemos.Models;
using Mnemos.Models.Interfaces;
using Mnemos.ViewModels;

namespace Mnemos.Controllers
{
	[Authorize]
	public class ThemesController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;

		public ThemesController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		public IActionResult Index()
		{
			return View(_unitOfWork.Themes.Find(t => t.User.Login == HttpContext.User.Identity.Name));
		}

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(ThemeModel modal)
		{
			if (!ModelState.IsValid)
			{
				return View(modal);
			}

			var user = await _unitOfWork.Users.FirstOrDefaultAsync(u => u.Login == HttpContext.User.Identity.Name);
			var theme = new Theme
			{
				UserId = user.Id,
				Name = modal.Name,
				Description = modal.Description
			};

			_unitOfWork.Themes.Add(theme);
			_unitOfWork.Complete();

			return RedirectToAction(nameof(Index));
		}

		[HttpGet]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var theme = await _unitOfWork.Themes.GetByIdAsync((int) id);
			if (theme == null)
			{
				return NotFound();
			}

			return View(new ThemeModel {Name = theme.Name, Description = theme.Description});
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, ThemeModel model)
		{
			if (!ModelState.IsValid)
			{
				return View(model);
			}

			var theme = await _unitOfWork.Themes.GetByIdAsync(id);
			if (theme == null)
			{
				return NotFound();
			}

			theme.Name = model.Name;
			theme.Description = model.Description;

			_unitOfWork.Themes.Update(theme);
			_unitOfWork.Complete();

			return RedirectToAction(nameof(Index));
		}

		[HttpGet]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var theme = await _unitOfWork.Themes.GetByIdAsync((int) id);

			if (theme == null)
			{
				return NotFound();
			}

			return View(theme);
		}

		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var theme = await _unitOfWork.Themes.GetByIdAsync(id);
			_unitOfWork.Themes.Remove(theme);
			_unitOfWork.Complete();
			return RedirectToAction(nameof(Index));
		}
	}
}

Mnemos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mnemos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mnemos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house"></i> Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Repeats" asp-action="Index"><i class="bi bi-arrow-repeat"></i> Repetition</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Themes" asp-action="Index"><i class="bi bi-clipboard"></i> Themes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Questions" asp-action="Index"><i class="bi bi-question-circle"></i> Questions</a>
                        </li>
                        @if(!string.IsNullOrEmpty(User.Identity?.Name)) {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout"><i class="bi bi-box-arrow-right"></i> Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Mnemos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>